### ISSUE TITLE
As a person, I would like to able to access the index page https://aau-giraf.github.io/, I expect an index page which redirect either https://giraf.cs.aau.dk/ or https://aau-giraf.github.io/wiki/, such that i dont see a broken page.

### ISSUE THREAD

**Issue by Jaffenheimer** [aau-giraf/.github#10]
Dette er en issue der kommer fra ulrik, han ønsker at få løst hurtigst muligt.

User story
As a person, I would like to able to access the index page https://aau-giraf.github.io/, I expect an index page which redirect either https://giraf.cs.aau.dk/ or https://aau-giraf.github.io/wiki/, such that i dont see a broken page.

Jeg ved ikke lige hvilke actors (<person>) som i har valgt at bruge. 

Potentiel løsning
Jeg ville vælge https://aau-giraf.github.io/wiki/ hvis https://aau-giraf.github.io/ hovedsageligt målrettet udviklingsprocessen.

**Comment by Lildhansen** [comment]
Resolved in a newly created repository with this commit:
https://github.com/aau-giraf/aau-giraf.github.io/commit/8b8a99fc7bdc0148594c4324fc5063120adb7cd9
