### ISSUE TITLE
Find where the original master branch has dissapeared

### ISSUE THREAD

**Issue by JakobTopholt** [aau-giraf/.github#11]
Description
The master branch was merged into the develop back in 2020 (we think), we'd like to have a master branch once again so that (I forgot the reason please write the reason if you read this)

Possible Suggested Solution
Find the last release of Giraf, and see if the master branch of that release can be restored.

https://github.com/aau-giraf/web-api/commit/cd61cbcd2be8f3dd55829e41b9ed86b9f56e960b

**Comment by Jaffenheimer** [comment]
Not necessary closing this
