### ISSUE TITLE
As a developer i would like to be able to make new releases to production

### ISSUE THREAD

**Issue by Jaffenheimer** [aau-giraf/.github#12]
As a developer i would like to be able to make new releases to production.
Currently given the missing master branch, we have no ability to make a new release to production.
Furthermore it would not be possible to make a release without all the integration tests passing.

Potential fixes:
Find the master branch as in #11 and make sure all tests passes.
Figure out how the release specific files work and edit them so we can make a new release fixing multiple issues.

**Comment by JakobTopholt** [comment]
Duplicate
