### ISSUE TITLE
Make the setup guide more user friendly (on wiki, optionally also pdf and a video)

### ISSUE THREAD

**Issue by JakobTopholt** [aau-giraf/.github#9]
Currently some developers have had issues setting up their build environment.

The current build guide is good, but it could be better.

Suggestions:

The setup guide should have a video accompanying it and a list of the most common errors found at which point in the video and their fixes.

All expressions in the setup guide should be written so that there could be no misunderstanding.

the new setup guide should as rule of thumb be a rewriting of the old setup guide incorporating

- [x]  For Windows
- [ ]  For mac
- [ ] For Linux (Ubuntu)

here are Andreas' slides
https://docs.google.com/presentation/d/1wUlsN_26hOQpMboZCnlr_8xTrwsJWvtxVMpx3vxnpao/edit#slide=id.gfe6c2644ab_0_0

**Comment by JakobTopholt** [comment]
Currently some developers have had issues setting up their build environment.

The current build guide is good, but it could be better.

Suggestions:

1. The setup guide should have a video accompanying it and a list of the most common errors found at which point in the video and their fixes.

2. All expressions in the setup guide should be written so that there could be no misunderstanding.

3. the new setup guide should as rule of thumb be a rewriting of the old setup guide incorporating

**Comment by andreaslborg** [comment]
Suggestion: Would a video guide be practical? If so, consider making one for the following year's students.
